apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: task-ingress
spec:
  ingressClassName: nginx
  rules:
  - host: "*.amazonaws.com"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: spring-boot
            port:
              number: 8080
