kind: Deployment
apiVersion: apps/v1
metadata:
  name: spring-boot
  namespace: ingress-nginx
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: web-spring-boot
  template:
    metadata:
      labels:
        app: web-spring-boot
    spec:
      containers:
        - name: spring-boot
          image: sameergaikwad17/simple-spring-boot:jdk8
          imagePullPolicy: Always
          ports:
             - containerPort: 8080
          resources:
            requests:
              memory: "50Mi"
              cpu: "500m"
            limits:
              memory: "500Mi"
              cpu: "2000m"
